# Tableau Météo

# bc4dc1     # Poupre
# cf80d3     # Poupre claire
# 00CEC8     # Bleu vert
# 90D5FF     # Bleu
# 52D6FC     # Bleu moyen
# 93E3FD     # Bleu claire
# 00ff13     # vert
# FFED52     # jaune 
# FDBA6F     # Orange
# FF5B61     # Rouge

views:
  - title: Home
    type: panel
    theme: LCARS Lower Decks I
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: custom:horizontal-layout
                layout:
                  width: 300
                cards:
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: header-left
                    content: |
                      <h1>Intérieure</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >- 
                       {{ states('sensor.maison_temperature') }}
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                          font-size: 160px !important;
                          line-height: 161px !important;
                          {% set teint = states('sensor.maison_temperature') | float(0) %}
                          {% if teint < 18 %} color:#bc4dc1 !important;     # Poupre   
                          {% elif teint < 20 %} color:#90D5FF !important;   # Bleu 
                          {% elif teint < 23 %} color:#00ff13 !important;   # vert  
                          {% elif teint < 25 %} color:#FFED52 !important;  # jaune 
                          {% else %} color:#FF5B61  !important;             # Rouge
                          {% endif %} 
                         }
                         
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Extérieure</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {{ states('sensor.tempest_st_00032986_temperature') |
                      round(1) }}
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            {% set teext = states('sensor.tempest_st_00032986_temperature') | float(0) %}
                            {% if teext < -25 %} color:#bc4dc1 !important;     # Poupre     
                            {% elif teext < -20 %} color:#cf80d3 !important;   # Poupre claire 
                            {% elif teext < -15 %} color:#00CEC8 !important;   # Bleu vert
                            {% elif teext < 0 %} color:#90D5FF !important;     # Bleu
                            {% elif teext < 15 %} color:#52D6FC !important;    # Bleu moyen
                            {% elif teext < 20 %} color:#93E3FD !important;    # Bleu claire
                            {% elif teext < 25 %} color:#00ff13 !important;    # vert     
                            {% elif teext < 30 %} color:#FFED52 !important;    # jaune 
                            {% elif teext < 35 %} color:#FDBA6F !important;    # Orange   
                            {% else %} color:#FF5B61 !important;               # Rouge              
                            {% endif %} 
                         }
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Vistesse du vent</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {% set vent = states('sensor.tempest_st_00032986_wind_speed') | float(0)
                      %} {% if vent > 0 %}
                         {{ states('sensor.tempest_st_00032986_wind_speed') | round(1) }}
                      {% else %} 
                         {{ states('sensor.tempest_st_00032986_wind_direction_avg') }}
                      {% endif %}  
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            {% set vent = states('sensor.tempest_st_00032986_wind_speed') | float(0) %}
                            {% if vent == 0 %} color:#FFFFFF !important;       # Blanc
                            {% elif vent < 10 %} color:#00ff13 !important;     # vert     
                            {% elif vent < 15 %} color:#FFED52 !important;     # jaune 
                            {% elif vent < 20 %} color:#FDBA6F !important;     # Orange   
                            {% else %} color:#FF5B61 !important;               # Rouge              
                            {% endif %} 
                         }
                      
                  - type: custom:html-card
                    title: ''
                    content: '&nbsp;'
                    card_mod:
                      class: footer-left
                      
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: custom:horizontal-layout
                layout:
                  width: 300
                cards:
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: header-left
                    content: |
                      <h1>[[sensor.date_du_jour]]</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: '{{ now().strftime(''%H:%M'') }}'
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            color:#FFFFFF !important; # Blanc
                         }
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Index UV - Bruit</h1>

                  - type: custom:mushroom-template-card
                    primary: >-
                      {% set iuv = states('sensor.tempest_st_00032986_uv_index') | float(0)
                      %} {% if iuv > 0 %}
                         {{ states('sensor.tempest_st_00032986_uv_index') | round(2) }}
                      {% else %} 
                         {{ states('sensor.maison_bruit') | int(0) }}
                      {% endif %} 
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            {% set iuv = states('sensor.tempest_st_00032986_uv_index') | float(0) %}
                            {% set bruit = states('sensor.maison_bruit') | int(0)  %}
                            {% if iuv > 0 %} 
                              {% if iuv < 3 %} color:#00ff13 !important;       # Vert
                              {% elif iuv < 6 %} color:#FFED52 !important;     # Jaune
                              {% elif iuv < 8 %} color:#FDBA6F !important;     # Orange
                              {% elif iuv < 11 %} color:#FF5B61 !important;    # Rouge
                              {% else %} color:#bc4dc1 !important;             # Poupre
                              {% endif %}
                            {% else %}
                              {% if bruit < 60 %} color:#00ff13 !important;       # Vert
                              {% elif bruit < 90 %} color:#FFED52 !important;     # Jaune
                              {% elif bruit < 110 %} color:#FDBA6F !important;    # Orange
                              {% elif bruit < 130 %} color:#FF5B61 !important;    # Rouge
                              {% else %} color:#bc4dc1 !important;                # Poupre
                              {% endif %}  
                            {% endif %} 
                         }
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>IQA</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {{
                      states('sensor.mauricie_quebec_canada_indice_de_qualite_de_l_air')
                      }} 
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            {% set aqi = states('sensor.mauricie_quebec_canada_indice_de_qualite_de_l_air') | int(0) %}
                            {% if aqi < 50 %} color:#00ff13 !important;        # Vert
                            {% elif aqi < 100 %} color:#FFED52 !important;     # Jaune
                            {% elif aqi < 160 %} color:#FDBA6F !important;     # Orange
                            {% elif aqi < 200 %} color:#FF5B61 !important;     # Rouge
                            {% else %} color:#bc4dc1 !important;               # Poupre
                            {% endif %} 
                         }
                      
                  - type: custom:html-card
                    title: ''
                    content: '&nbsp;'
                    card_mod:
                      class: footer-left
                      
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: custom:horizontal-layout
                layout:
                  width: 300
                cards:
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: header-left
                    content: |
                      <h1>Pluies - CO2</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {% set pluie = states('sensor.tempest_st_00032986_rain_today') | float(0) %}
                      {% if pluie < 1 %}
                         {{ states('sensor.maison_dioxyde_de_carbone') | int(0) }}
                      {% else %} 
                         {{ states('sensor.tempest_st_00032986_rain_today') | round(2) }}
                      {% endif %} 
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            {% set pluie = states('sensor.tempest_st_00032986_rain_today') | float(0) %}
                            {% set co2 = states('sensor.maison_dioxyde_de_carbone') | int(0) %}
                            {% if pluie < 1 %}
                              {% if co2 < 800 %} color:#00ff13 !important;     # Vert
                              {% elif co2 < 1200 %} color:#FFED52 !important;  # Jaune
                              {% elif co2 < 1800 %} color:#FDBA6F !important;  # Orange
                              {% else %} color:#FF5B61 !important;             # Rouge 
                              {% endif %}
                            {% else %}
                              {% if pluie < 10 %} color:#00ff13 !important;       # Vert
                              {% elif pluie < 15 %} color:#FFED52 !important;     # Jaune
                              {% elif pluie < 20 %} color:#FDBA6F !important;     # Orange
                              {% elif pluie < 25 %} color:#FF5B61 !important;     # Rouge
                              {% else %} color:#bc4dc1 !important;                # Poupre
                              {% endif %}  
                            {% endif %} 
                         }
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Humidité - Taux pluie</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {% set taux = states('sensor.tempest_st_00032986_rain_rate') | float(0)
                      %} {% if taux > 0 %}
                         {{ states('sensor.tempest_st_00032986_rain_rate') | round(2) }}
                      {% else %} 
                         {{ states('sensor.tempest_st_00032986_humidity') | round(1) }}
                      {% endif %} 
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            {% set taux = states('sensor.tempest_st_00032986_rain_rate') | float(0) %}
                            {% if taux > 0 %}
                              {% if taux < 10 %} color:#00ff13 !important;       # Vert
                              {% elif taux < 15 %} color:#FFED52 !important;     # Jaune
                              {% elif taux < 20 %} color:#FDBA6F !important;     # Orange
                              {% else %} color:#FF5B61 !important;               # Rouge
                              {% endif %} 
                            {% else %} 
                              color:#FFFFFF !important; # Blanc
                            {% endif %} 
                         }
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Pression</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {{ states('sensor.tempest_st_00032986_station_pressure') 
                      | round(1) }} 
                    tap_action:
                      action: none
                    card_mod:
                      class: middle-left
                      style:
                        ha-tile-info$: |
                         :host {
                          width: 100%;
                          text-align: center !important;
                         }
                         .primary {
                            font-size: 160px !important;
                            line-height: 161px !important;
                            {% set niv = states('sensor.tempest_st_00032986_pressure_trend') %}
                            {% if niv == 'Falling' %} color:#FFED52 !important;   # Jaune
                            {% elif niv == 'Rising' %} color:#00ff13 !important; # Vert
                            {% else %} color:#FFFFFF !important;          # Blanc
                            {% endif %} 
                         }
                  - type: custom:html-card
                    title: ''
                    content: '&nbsp;'
                    card_mod:
                      class: footer-left
  - type: panel
    path: parmetres
    title: Parmètres
    icon: mdi:tools
    theme: LCARS Lower Decks I
    cards:
      - type: vertical-stack
        cards:
          - type: custom:html-card
            title: ''
            content: '&nbsp;'
            card_mod:
              class: middle-blank
              
          - type: custom:html-card
            title: ''
            content: |
              <h1>Paramètres</h1>
            card_mod:
              class: header-contained
              
          - type: entities
            entities:
              - entity: input_boolean.lcars_sound
                icon: mdi:speaker
              - entity: input_boolean.lcars_texture
                icon: mdi:texture
              - entity: input_number.lcars_horizontal
              - entity: input_number.lcars_vertical
            state_color: true
            card_mod:
              class: middle-contained
          - type: custom:html-card
            title: ''
            content: |
              <h1>&nbsp;</h1>
            card_mod:
              class: footer-contained
